Repository wecode-bootcamp-korea/27-1st-Bagettt-backend, pull requests merged in 2021-12, with the labels that each got.

#2 [Create] bagettt 모델링 생성
  bagettt/settings.py
  bagettt/urls.py
  packages/__init__.py
  packages/admin.py
  packages/apps.py
  packages/migrations/0001_initial.py
  packages/migrations/0002_initial.py
  packages/migrations/__init__.py
  packages/models.py
  packages/tests.py
  packages/urls.py
  packages/views.py
  shops/__init__.py
  shops/admin.py
  shops/apps.py
  shops/migrations/0001_initial.py
  shops/migrations/__init__.py
  shops/models.py
  shops/tests.py
  shops/urls.py
  shops/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: Accepted

#4 [CREATE] SignUpview
  users/urls.py
  users/validaitor.py
  users/views.py
Labels: Status: 수정 요청

#6 [Modify] models 수정
  bagettt/settings.py
  core/utils/decorator_sign_in.py
  core/utils/validator.py
  packages/migrations/0001_initial.py
  packages/models.py
  packages/urls.py
  shops/migrations/0001_initial.py
  shops/models.py
  shops/urls.py
  shops/views.py
  users/migrations/0001_initial.py
  users/views.py
  validator.py
Labels: Status: 리뷰 요청

#5 [CREATE] SignInView
  core/decorator.py
  shops/models.py
  users/urls.py
  users/validaitor.py
  users/views.py
Labels: Status: 리뷰 요청

#9 [Modify] Shops.models.py
  core/utils/decorator_sign_in.py
  core/utils/validator.py
  shops/migrations/0002_alter_option_shipping_option.py
  shops/models.py
  validator.py
Labels: Status: 리뷰 요청

#10 [Modify] Shops app_Class Cart, OrderItem
  shops/migrations/0003_alter_orderitem_quantity.py
  shops/migrations/0004_alter_cart_quantity.py
  shops/migrations/0005_auto_20211208_0655.py
  shops/models.py
Labels: Status: 리뷰 요청

#7 [Create] PackagesListView, ProductsView
  core/utils/decorator.py
  core/utils/validator.py
  packages/urls.py
  packages/views.py
Labels: Status: 리뷰 요청

#8 [Create] Shops : CRUD
  core/utils/decorator.py
  core/utils/validator.py
  shops/views.py
  users/views.py
Labels: Status: 리뷰 요청

#13 [Create] cartview_order page
  packages/views.py
  shops/migrations/0007_alter_cart_price.py
  shops/models.py
  shops/urls.py
  shops/views.py
Labels: Status: 리뷰 요청
